### ISSUE TITLE
Incorrect keys extracted

### ISSUE THREAD

**Issue by TomaszCz** [vendure-ecommerce/ngx-translate-extract#12]
Hey guys, this is great library! I appreciate you took over the maintenance.

I find some edge cases using this library and i failed to eliminate them with build in parameters. The only way to address that was to refactor my code / or filter output of the script.

It seem the code extract keys from any chained methods to .instant() usage e.g. 'replace' and 'split' contained strings.

![image](https://github.com/vendure-ecommerce/ngx-translate-extract/assets/20865719/71c33296-752e-4245-aacf-4e56de66a811)
![image](https://github.com/vendure-ecommerce/ngx-translate-extract/assets/20865719/85413c46-9cfc-48d3-b27b-1b02f557cbed)

I guess this is taking full array. https://github.com/vendure-ecommerce/ngx-translate-extract/blob/master/src/utils/ast-helpers.ts#L56

**Comment by michaelbromley** [comment]
Hi,
Thanks for the report! 

I've marked this as "help wanted" because I don't have time to address this right now. Anyone who feels like tackling this, please let me know 🙏

**Comment by bastianjoel** [comment]
Not entirely sure but I think we have a fix for that in our fork: https://github.com/OpenSlides/ngx-translate-extract/commit/b3d35b6ee1e9bccade7dc0c492ed0f3b8dac55b8
