### ISSUE TITLE
An error occurred: SyntaxError: Expected double-quoted property name in JSON at position 908

### ISSUE THREAD

**Issue by neverlose-lv** [vendure-ecommerce/ngx-translate-extract#24]
After updating to version 8.2.3 I receive an error, when try to extract the translations.
There is no such error when I use version 8.2.2

```
An error occurred: SyntaxError: Expected double-quoted property name in JSON at position 908
```

**Comment by michaelbromley** [comment]
Hi, thanks for the report. Is there any stack trace with this error?

**Comment by sod** [comment]
It's the [`tsconfig`](https://github.com/vendure-ecommerce/ngx-translate-extract/blob/master/package.json#L24) dependency. The `loadSync` method call in the end, if it finds a tsconfig.json, will do `JSON.parse` on its contents:

![CleanShot 2023-10-06 at 13 32 27@2x](https://github.com/vendure-ecommerce/ngx-translate-extract/assets/905328/8a2b39c2-4129-401b-a1b3-2c003e306e39)

But typescript doesn't use a pure JSON. they use their own parser, thats kinda json5'ish. It e.g. allows comments and dangling commas.

There is an issue for it https://github.com/TypeStrong/tsconfig/issues/30, but as the last change for that library was 5 years ago, I double someone may touch it.

What this lib is concerned, the easiest fix may be, to replace `loadSync` usage with `resolveSync (from npm:tsconfig) => fs.readFileSync (from node:fs) => json5.parse (from npm:json5)`.

Well, or you go through your tsconfigs and remove dangling commas/make them valid JSON :)
