### ISSUE TITLE
Parse issue with self closing tag

### ISSUE THREAD

**Issue by medbenmakhlouf** [vendure-ecommerce/ngx-translate-extract#3]
Angular@15.1 introduces the self closing tag. however, the extractor will not be able to detect/extract the translations.

an example : 

This works fine : 

```
<ion-infinite-scroll threshold="100px" (ionInfinite)="loadData($event)">
  <ion-infinite-scroll-content loadingText="{{ 'Loading...' | translate }}"></ion-infinite-scroll-content>
</ion-infinite-scroll>

```

but this is not working : 

```
<ion-infinite-scroll  threshold="100px" (ionInfinite)="loadData($event)">
  <ion-infinite-scroll-content loadingText="{{ 'Loading...' | translate }}" />
</ion-infinite-scroll>

```

**Comment by tmijieux** [comment]
after i tested locally, I think just updating the @angular/compiler to latest 15.x version seems to do the trick...

**Comment by michaelbromley** [comment]
Should this package even have a dependency on the angular compiler? Does it not make more sense to just have it as a peer dependency with a loose range and assume the consuming project will have the compiler available?
