### ISSUE TITLE
TranslateService used as an injected const does not work in a const method (like HttpInterceptorFn)

### ISSUE THREAD

**Issue by Laurensvdw** [vendure-ecommerce/ngx-translate-extract#44]
A fix was done for readonly inject earlier in version 9.1.1. Additionally somewhat related support is required for cases like ResolveFn, HttpInterceptorFn,... which are const's rather than classes.

In ng14 or something the following syntax 
`@Injectable()
export class ErrorToastInterceptor implements HttpInterceptor {`
was (optionally) changed to
`export const errorToastInterceptor: HttpInterceptorFn = (req: HttpRequest<unknown>, next: HttpHandlerFn) => {`

Where the TranslationService is injected as a const, like:
`const translateService = inject(TranslateService);`

`translateService.instant('KEY_NAME')` is unfortunately not picked up :( I guess a method has to be added to the ast-helpers.ts to find the const translateService injectable, in a const method. 

Thanks for looking into it!

**Comment by andrea-spotsoftware** [comment]
@Laurensvdw looks like that problem exists for all functions. 
I'm using ngrx signal store and there are a lot of functions with injected TranslateService instance. Unfortunately, everything is ignored by the extract tool.

**Comment by pmpak** [comment]
This is happening because the service parser checks only inside class declarations. I did an attempt to extend it and see if it would have been easy to parse function expressions but while it looked that it worked it fell apart in some edge cases. For example, from the code below it extracted the `' , '` from the join instead of the `translation.key`

```typescript
export const errorInterceptor: HttpInterceptorFn = (req, next) => {
  const translateService = inject(TranslateService);
  const router = inject(Router);

  translateService.instant('translation.key').join(', ');
};
```
I will give it another try when I find some more time to check it out.

**Comment by michaelbromley** [comment]
This is now published as a pre-release `v9.2.0-next.0`, under the "next" tag. Let me know any feedback once you have tried it on your code base and all being well, I'll do a general release.

**Comment by Laurensvdw** [comment]
I would gladly test this but the client's apps are still on Angular 16, being 8.x of this package 😭 Quite an important detail I forgot to mention... So move along, we'll update probably during the summer. 😨 As LTS is 8 Nov. 2024 for ng16

**Comment by pmpak** [comment]
@michaelbromley I tested it in a project with ~10.000 keys and there was no issues with the 9.2.0-next.0 👍
