### ISSUE TITLE
ngx-translate v16

### ISSUE THREAD

**Issue by CodeAndWeb** [vendure-ecommerce/ngx-translate-extract#56]
I am Andreas Löw and started maintaining ngx-translate... and just released v16

I've added the marker function to the core to make it available for other scenarios, too - e.g. when using with a translation tool like [BabelEdit](https://(www.codeandweb.com/babeledit). Would be great if you could update your package to support that one for extraction, too.

See:
https://ngx-translate.org/getting-started/migration-guide/#23-using-the-ngx-translate-_-marker-function

**Comment by CodeAndWeb** [comment]
Can you please publish the update? I'd like to add a section about this plugin to the ngx-translate.org documentation... but it currently does not work without this change.

**Comment by pmpak** [comment]
Unfortunately, I don’t have permissions to merge and release, but @michaelbromley  is usually quite responsive with issues and PRs, so I expect this will be reviewed soon.

**Comment by michaelbromley** [comment]
Hi guys. It's on my radar. This week is mega busy but I'll get to this soon 👍

**Comment by michaelbromley** [comment]
v9.3.0 was just published. Thanks for the contribution!
