### ISSUE TITLE
9.3.0 named export 'isCallExpression' not found

### ISSUE THREAD

**Issue by Laurensvdw** [vendure-ecommerce/ngx-translate-extract#58]
Hi, a colleague just installed a new project with latest dependencies. Automatically 9.3.0 was pulled which causes errors when running ngx-translate-extract. It tries to use a method from typscript which is unknown. We are running typescript version:
`"typescript": "~5.4.5"`

Thanks!

![image](https://github.com/user-attachments/assets/4a549cb3-0e84-4e43-8803-289d6d0fa0bd)

**Comment by pmpak** [comment]
Hello, this is a side effect caused by #55. I'm looking into that.
