### ISSUE TITLE
Translation extract throwing error for Angular 14

### ISSUE THREAD

**Issue by Sujay-shetty** [vendure-ecommerce/ngx-translate-extract#6]
Hi,

Since translation extract got error while migrated from Angular 12 to 14 but after following below thread tried integrating the library

https://github.com/biesbjerg/ngx-translate-extract/issues/246#issuecomment-1353101571

But facing below issue when translation extract command is executed

`> ngx-translate-extract --input ./src --output ./src/translations/template.pot --format=pot --clean --sort --marker marker

(node:11858) UnhandledPromiseRejectionWarning: Error: Not supported
    at Object.<anonymous> (/var/jenkins/workspace/sources/project/node_modules/@vendure/ngx-translate-extract/bin/cli.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
(node:11858) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11858) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Could you please help me in resolving the issue?
@michaelbromley

Thanks,
Sujay

**Comment by michaelbromley** [comment]
Hi,

What version of node are you using?

**Comment by michaelbromley** [comment]
Closing due to lack of response.
