### ISSUE TITLE
Absolute source location in team projects

### ISSUE THREAD

**Issue by nboisnea** [vendure-ecommerce/ngx-translate-extract#63]
The source location of a translation code that is added as a comment in the PO files can be really annoying for team projects, since it is an absolute path. Each time a developer adds a translations it is commented with the path to the source file on their local machine.
This is not really useful and needs to be removed manually every time.
Improvement ideas:
- Make optional with a flag
- Keep only the file name
- Use a relative path from project's root/current dir

I'd go with the flag since I'd rather not have these comments added to the PO file.

**Comment by pmpak** [comment]
Absolute paths in source location comments can be problematic indeed and looks like an issue of the default behavior. Using the relative path looks more sensible approach. I'll try to fix this and then see the potential for a new flag to disable the comments entirely.

**Comment by nboisnea** [comment]
@pmpak Great, thank you! That would definitely be an improvement!
Although for our use case we look forward to the flag for disabling source location, since translations don't always relate to a single file but instead can be sourced from multiple templates. Ctrl+Shift+F the project is much easier for finding where a translation is used.
